# These are supported funding model platforms

github: #VShawn
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: VShawn
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom:
  [
    "https://www.paypal.me/ShawnVeck",
    "https://github.com/1Remote/1Remote.github.io/blob/main/source/docs/zh-cn/donate.jpg",
  ]
